version: '3.9'

networks:
  fuel-notifier-net:
    name: fuel-notifier-net

services:
  queue:
      container_name: fuel-notifier-redis
      image: redis:7.2.3
      networks:
        - fuel-notifier-net
      ports:
        - "60000:6379"
  #postgres_db:
  #  container_name: dockerissimo-postgres
  #  image: postgres:16.0
  #  networks:
  #    - dockerissimo-net
  #  environment:
  #    - POSTGRES_USER=dockerissimo_rust
  #    - POSTGRES_PASSWORD=pass
  #    - POSTGRES_DB=fantastic_db
    #volumes:
    #  - db_data:/var/lib/postgresql/data
    #  - db_pgdata:/var/lib/postgresql/data/pgdata
  #  ports:
  #    - "5432:5432"
  #app:
  #  container_name: fuel-notifier-rust
  #  build:
  #    context: .
  #    network: host
  #  depends_on:
  #    - postgres_db
  #    - queue
  #  environment:
  #    - NOTIFICATION_GROUP=notification_listeners
  #    - CONSUMER_NAME=notifier-1
  #    - BLOCK_TIME=60
  #    - STREAM_NAME=streams:notifications
  #    - REDIS_URL=redis://queue
  #    - ITEM_COUNT=10
  #  networks:
  #    - dockerissimo-net
  #  environment:
  #    - CONN_URI=postgresql://dockerissimo_rust:pass@postgres_db:5432/fantastic_db
  #    - RUST_LOG=trace
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - ./src:/code/src
  #  entrypoint: ["cargo", "watch", "-x", "run -- --conf-path=2 --templates-path=4"]